import { Html, Text, Heading, Section, Container } from "@react-email/components";
import * as React from "react";

interface ContactSubmissionProps {
  firstname: string;
  lastname: string;
  email: string;
  subject: string;
  message: string;
}

const ContactSubmissionEmail = ({
  firstname,
  lastname,
  email,
  subject,
  message,
}: ContactSubmissionProps) => {
  return (
    <Html>
      <Container
        style={{
          fontFamily: "Arial, sans-serif",
          backgroundColor: "#f4f4f4",
          padding: "20px",
          borderRadius: "8px",
        }}
      >
        <Section style={{ marginBottom: "20px" }}>
          <Heading
            style={{
              color: "#333",
              fontSize: "24px",
              fontWeight: "bold",
              textAlign: "center",
              marginBottom: "10px",
            }}
          >
            New Contact Form Submission
          </Heading>
        </Section>

        <Section>
          <Text style={{ fontSize: "16px", marginBottom: "8px" }}>
            <strong>First Name:</strong> {firstname}
          </Text>
          <Text style={{ fontSize: "16px", marginBottom: "8px" }}>
            <strong>Last Name:</strong> {lastname}
          </Text>
          <Text style={{ fontSize: "16px", marginBottom: "8px" }}>
            <strong>Email:</strong> {email}
          </Text>
          <Text style={{ fontSize: "16px", marginBottom: "8px" }}>
            <strong>Subject:</strong> {subject}
          </Text>
        </Section>

        <Section>
          <Heading
            style={{
              fontSize: "18px",
              marginTop: "20px",
              marginBottom: "10px",
              color: "#555",
            }}
          >
            Message:
          </Heading>
          <Text
            style={{
              backgroundColor: "#fff",
              padding: "15px",
              borderRadius: "5px",
              border: "1px solid #ddd",
              lineHeight: "1.5",
              fontSize: "16px",
            }}
          >
            {message}
          </Text>
        </Section>

        <Section style={{ marginTop: "30px", textAlign: "center" }}>
          <Text style={{ fontSize: "14px", color: "#888" }}>
            This email was generated by your website&apos;s contact form.
          </Text>
        </Section>
      </Container>
    </Html>
  );
};

export default ContactSubmissionEmail;