import type { Metadata } from "next";
import {Ubuntu_Mono} from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const ubuntuMono = Ubuntu_Mono({
  subsets: ["latin"],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Pedro C. | Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuMono.className} antialiased bg-licorice text-honeydew`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
